VipSoft.Web/Areas/VipSoft/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VipSoft.Web.Areas.VipSoft.Controllers
{
    public class MainController : Controller
    {
        //
        // GET: /Main/

        public ActionResult Index()
        {
            if(Session["UserName"]==null)
            {
                //return RedirectToAction("Login", "User");   
            }            
            return View();
        }

        public ActionResult Loginout()
        {
        
            Session["UserName"]=null;
            Response.Write("<script>alert('退出成功')</script>");

            return RedirectToAction("Login", "User"); 
        }

    }
}

VipSoft.Web/Areas/VipSoft/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VipSoft.Membership.Core.Entity;
using VipSoft.Membership.Core.Service;

namespace VipSoft.Web.Areas.VipSoft.Controllers
{
    public class MenuController : BaseController
    {
        //
        // GET: /Admin/Menu/                                                                                  
        public IMenuService MenuService = Wac.GetObject("MenuService") as IMenuService;

        public ActionResult AdminMenu(int pid = 0)
        {

            var list = MenuService.GetMenuList(new Menu() { Status = 1, Conditaion = "Status=[Status]", OrderBy = "ORDER BY sequence,id" });
            ViewData["AdminMenu"] = list;
            Session["MenuParentId"] = Session["MenuParentId"] ?? 101;
            if (pid > 0 && pid.ToString() != Session["MenuParentId"].ToString())
            {
                Session["MenuParentId"] = pid;
            }
            ViewBag.ParentId = Session["MenuParentId"] ?? 101;
            ViewBag.AreaName = AreaName;
            return View(list.ToList());
        }

        public ActionResult List(int cid = 0)
        {
            IList<Menu> list = new List<Menu>();
            MenuTreeTable(list, cid, 0);

            //var list = CategoryService.GetCategoryList(new Category { ParentId = cid, Conditaion = "parent_id=[ParentId];" });

            return View(list);
        }


        //方法待改造和迁移
        public void MenuTreeTable(IList<Menu> result, int parentId, int depth)
        {
            List<Menu> menuList = MenuService.GetMenuList(new Menu()).ToList();
            var list = menuList.FindAll(p => p.ParentId == parentId);
            foreach (var item in list)
            {
                var parentDsc = "treegrid-" + item.ID;
                item.DepthDescription = depth == 0 ? parentDsc : parentDsc + " treegrid-parent-" + item.ParentId;
                result.Add(item);
                MenuTreeTable(result, item.ID, item.Depth);
            }
        }
    }
}

VipSoft.Web/Areas/VipSoft/Views/Menu/AdminMenu.cshtml
@model List<VipSoft.Membership.Core.Entity.Menu>
@{ 
    var categoryIndex = 1;
    if (Request.RequestContext.RouteData.Values["cid"] != null)
    {
        try
        {
            categoryIndex = Convert.ToInt32(Request.RequestContext.RouteData.Values["cid"]);
        }
        catch
        {
            Response.Redirect("/VipSoft");
        }
    }
    var menuIndex = 1;
    if (Request.RequestContext.RouteData.Values["mid"] != null)
    {
        try
        {
            menuIndex = Convert.ToInt32(Request.RequestContext.RouteData.Values["mid"]);
        }
        catch
        {
            Response.Redirect("/VipSoft");
        }
    }
}

<div id="sidebar" class="sidebar responsive">
    <script type="text/javascript">
        try { ace.settings.check('sidebar', 'fixed') } catch (e) { }
    </script>

    <div class="sidebar-shortcuts" id="sidebar-shortcuts">
        <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
            <button class="btn btn-success">
                <i class="ace-icon fa fa-signal"></i>
            </button>
            <a class="btn btn-warning" href="@Url.Action("Index", "Main", new { pid = 101})" title="CMS">
                <i class="ace-icon fa fa-users"></i>
            </a>
            <a class="btn btn-danger" href="@Url.Action("Index", "Main", new { pid = 201})" title="用户管理">
                <i class="ace-icon fa fa-cogs"></i>
            </a>
            <button class="btn btn-info" href="@Url.Action("Index", "Main", new { pid = 201})" title="系统设置">
                <i class="ace-icon fa fa-pencil"></i>
            </button>
        </div>

        <div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
            <span class="btn btn-success"></span>

            <span class="btn btn-info"></span>

            <span class="btn btn-warning"></span>

            <span class="btn btn-danger"></span>
        </div>
    </div>
    <!-- /.sidebar-shortcuts -->

    <ul class="nav nav-list">
        <li class="active">
            <a href="/vipsoft/">
                <i class="menu-icon fa fa-tachometer"></i>
                <span class="menu-text"> 首页 </span>
            </a>

            <b class="arrow"></b>
        </li>
        @foreach (var menu in Model.FindAll(p => p.ParentId == ViewBag.ParentId))
        {
            <li @if (categoryIndex == @menu.ID){ @Html.Raw("class=\"active open\"")   }>
                <a href="#" class="dropdown-toggle">
                    <i class="menu-icon @menu.Icon"></i>
                    <span class="menu-text"> @menu.Name </span>
                    <b class="arrow fa fa-angle-down"></b>
                </a>
                <b class="arrow"></b>
                <ul class="submenu">
                    @foreach (var child in Model.FindAll(p => p.ParentId == menu.ID))
                    {
                        <li @if (menuIndex == @child.ID){ @Html.Raw("class=\"active\"")   }>
                            <a href="@child.Url">
                                <i class="menu-icon fa fa-caret-right"></i>
                                @child.Name
                            </a>
                            <b class="arrow"></b>
                        </li>
                    }
                </ul>
            </li>
        }
    </ul>

    <!-- /.nav-list -->

    <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
        <i class="ace-icon fa fa-angle-double-left" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
    </div>

    <script type="text/javascript">
        try { ace.settings.check('sidebar', 'collapsed') } catch (e) { }
    </script>
</div>

<!--
<div title="平台管理" iconcss="menu-icon-model" class="l-scroll">
    <ul id="global_channel_tree" style="margin-top: 3px;">
    </ul>
</div>
<div title="权限设置" iconcss="menu-icon-setting" style="display: none">
    <ul class="nlist">
        @foreach (var menu in Model.FindAll(p => p.ParentId == 201))
        {
            <li><a class="l-link" href="javascript:f_addTab('@menu.ID','@menu.Name','@menu.Url')">@menu.Name</a></li>
        }
    </ul>
</div>

<div title="控制面板" iconcss="menu-icon-setting">
    <ul class="nlist">
        <li><a class="l-link" href="javascript:f_addTab('UpdatePwd','修改密码','/VipSoft/User/ChangePassword')">修改密码</a></li>
    </ul>
</div>

<div title="权限管理" iconcss="menu-icon-plugins">
    <ul class="nlist">
        <li><a class="l-link" href="javascript:f_addTab('listpage31','权限列表','1.htm')">权限列表</a></li>
        <li><a class="l-link" href="javascript:f_addTab('listpage32','新闻采集','1.htm')">权限分配</a></li>
    </ul>
</div>
<div title="控制面板" iconcss="menu-icon-setting">
    <ul class="nlist">
        <li><a class="l-link" href="javascript:f_addTab('sys_config','系统设置','/category/')">系统设置</a></li>
    </ul>
</div>
-->

VipSoft.Web/Areas/VipSoft/Views/Menu/List.cshtml
@model System.Collections.Generic.IList<VipSoft.Membership.Core.Entity.Menu>

@using VipSoft.WebUtility
@using Webdiyer.WebControls.Mvc
@using VipSoft.Membership.Core.Entity
 
@using System.Web.Mvc.Html
@{
    ViewBag.Title = "菜单管理";
    Layout = "~/Areas/VipSoft/Views/Shared/_AdminLayout.cshtml";
}
<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="fa">
                    <i class="fa fa-th"></i>
                </span>
                <h5>菜单管理</h5>
                <div class="buttons">
                    <a title="Icon Title" class="btn" href="@Url.Action("Add", new { cid = @Request.RequestContext.RouteData.Values["cid"], mid = @Request.RequestContext.RouteData.Values["mid"] })"><i class="fa fa-plus"></i><span class="text">新增</span></a>
                </div>
            </div>
            <div class="widget-content nopadding"> 
                <table class="table tree table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th style="width: 30px">
                                <div class="icheckbox_flat-blue" style="position: relative;">
                                    <input type="checkbox" id="title-table-checkbox" name="title-table-checkbox" style="position: absolute; opacity: 0;">
                                    <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background-color: rgb(255, 255, 255); border: 0px; opacity: 0; background-position: initial initial; background-repeat: initial initial;"></ins>
                                </div>
                            </th>
                            <th style="width: 80px;">编号</th>
                            <th style="width: 150px;">名称</th>
                            <th style="width: 120px;">类别</th>
                            <th>地址</th> 
                            <th style="width: 80px;">行数</th>
                            <th style="width: 80px;">状态</th>
                            <th style="width: 200px;"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr class="@item.DepthDescription">
                                <td class="tdCenter">
                                    <input name="@item.ID" id="@item.ID" onclick="UnSelectAll('chkSelectAll')" type="checkbox" value="@item.ID"/>
                                </td>
                                <td class="tdCenter">
                                    @item.ID
                                </td>
                                <td>
                                    @item.Name
                                </td> 
                                <td>
                                    权限管理
                                </td>
                                <td>
                                    @item.Url
                                </td> 
                                <td>
                                    @item.PageSize
                                </td> 
                                <td class="tdCenter">
                                    @item.Status
                                </td>

                                <td class="tdCenter">
                                    <div class="btn-group">
                                        <button class="btn btn-purple btn-xs">
                                            特性</button>
                                        <button data-toggle="dropdown" class="btn btn-purple dropdown-toggle btn-xs">
                                            <span class="caret"></span>
                                        </button>
                                        <ul class="dropdown-menu dropdown-purple" style="text-align: left">
                                            <li><a href="#" onclick="unrealized()">禁用</a></li>
                                            <li><a href="#" onclick="unrealized()">权限</a></li>
                                        </ul>
                                    </div>
                                    <a class="btn btn-primary btn-xs" href="@Url.Action("Add", new { id = item.ID, cid = @Request.RequestContext.RouteData.Values["cid"], mid = @Request.RequestContext.RouteData.Values["mid"] })" >修改</a>
                                    <a class="btn btn-danger btn-xs" href="javascript:;" onclick="deleteUser(this,@item.ID)">删除</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
 
    
@section Script {
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.treegrid.js")" ></script>

    <script type="text/javascript">
        //定义mid,cid供VipSoft.CMS.Category.js中的变量使用。
        var mid = @Request.RequestContext.RouteData.Values["mid"];
        var cid = @Request.RequestContext.RouteData.Values["cid"];  
        $(document).ready(function () { 
            $('.tree').treegrid({
                treeColumn: 2,
                expanderExpandedClass: 'fa fa-chevron-down',
                expanderCollapsedClass: 'fa fa-chevron-right'
            }); 
        });
    </script>
} 