VipSoft.Web/Areas/VipSoft/Controllers/ConfigController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VipSoft.Web.Areas.VipSoft.Controllers
{
    public class ConfigController : Controller
    {
        //
        // GET: /VipSoft/Config/

        public ActionResult Index()
        {
            return View();
        }

    }
}

VipSoft.Web/Areas/VipSoft/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VipSoft.Membership.Core.Entity;
using VipSoft.Membership.Core.Service;

namespace VipSoft.Web.Areas.VipSoft.Controllers
{
    public class MenuController : BaseController
    {
        //
        // GET: /Admin/Menu/                                                                                  
        public IMenuService MenuService = Wac.GetObject("MenuService") as IMenuService;

        public ActionResult AdminMenu(int pid = 0)
        {

            var list = MenuService.GetMenuList(new Menu() { Status = 1, Conditaion = "Status=[Status]", OrderBy = "ORDER BY sequence,id" });
            ViewData["AdminMenu"] = list;
            Session["MenuParentId"] = Session["MenuParentId"] ?? 101;
            if (pid > 0 && pid.ToString() != Session["MenuParentId"].ToString())
            {
                Session["MenuParentId"] = pid;
            }
            ViewBag.ParentId = Session["MenuParentId"] ?? 101;
            ViewBag.AreaName = AreaName;
            return View(list.ToList());
        }

        public ActionResult List(int cid = 0)
        {
            IList<Menu> list = new List<Menu>();
            MenuTreeTable(list, cid, 0);

            //var list = CategoryService.GetCategoryList(new Category { ParentId = cid, Conditaion = "parent_id=[ParentId];" });

            return View(list);
        }


        //方法待改造和迁移
        public void MenuTreeTable(IList<Menu> result, int parentId, int depth)
        {
            List<Menu> menuList = MenuService.GetMenuList(new Menu()).ToList();
            var list = menuList.FindAll(p => p.ParentId == parentId);
            foreach (var item in list)
            {
                var parentDsc = "treegrid-" + item.ID;
                item.DepthDescription = depth == 0 ? parentDsc : parentDsc + " treegrid-parent-" + item.ParentId;
                result.Add(item);
                MenuTreeTable(result, item.ID, item.Depth);
            }
        }
    }
}

VipSoft.Web/Areas/VipSoft/Controllers/UserController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="UserController.cs" company="VipSoft.com.cn">
//    Author:Chen,Jun
//        QQ:47262947
//     Email:chenjun@VipSoft.com.cn
//    Create:16-April-2013
// </copyright>


using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VipSoft.Membership.Core.Entity;
using VipSoft.Membership.Core.Service;
using Webdiyer.WebControls.Mvc;

namespace VipSoft.Web.Areas.VipSoft.Controllers
{
    public class UserController : BaseController
    {
        private static IUserService UserService = Wac.GetObject("UserService") as IUserService;

        #region View

        public ActionResult Add(int id = 0)
        {
            Users model = null;
            if (id > 0)
            {
                model = UserService.GetUser(id);
            }
            ViewBag.SubTitle = GetCurrentMenu.Name;
            return View(model);
        }

        public ActionResult List(int page = 1)
        {
            PagedList<Users> list = UserService.GetUserList(new Users()).ToPagedList(page, PageSize);
            ViewBag.SubTitle = GetCurrentMenu.Name;
            return View(list);
        }

        public ActionResult Login(int id = 0, int cid = -1)
        {
            Session["UserName"] = null;
            return View();
        }

        public ActionResult ChangePassword()
        {
            return View();
        }

        #endregion

        #region Action


        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Login(Users user)
        {
            user.Conditaion = "user_name=[UserName];AND Password = [Password];";
            if (!string.IsNullOrEmpty(user.UserName) && !string.IsNullOrEmpty(user.Password))
            {
                var model = UserService.GetUser(user);
                if (model != null)
                {
                    Session["UserName"] = model.UserName;
                    return RedirectToAction("Index", "Main");
                }
                ModelState.AddModelError("", "用户名或密码错误！");
            }
            else
            {
                ModelState.AddModelError("", "用户名或密码不能为空！");
            }
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public JsonResult SaveUser(Users user)
        {
            var result = 0;
            user.UpdateDate = DateTime.Now;
            var flag = (user.ID != 0 ? UserService.UpdateUser(user) : UserService.AddUser(user)) > 0;
            if (flag)
            {
                result = 1;
                //RedirectToAction("List");
            }
            return Json(result);
        }

        [HttpPost]
        public ActionResult Delete(int id = 0)
        {
            var result = UserService.DeleteUser(id);
            return Json(result);
        }



        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ChangePassword(FormCollection collection)
        {
            var oldPassword = collection["OldPassword"];
            var password = collection["Password"];
            var password1 = collection["Password1"];
            if (password != password1)
            {
                ModelState.AddModelError("", "两次密码不统一");
                return View();
            }
            var user = new Users
                           {
                               UserName = "admin",
                               Password = oldPassword,
                               Conditaion = "user_name=[UserName];AND Password = [Password];"
                           };
            var userlist = UserService.GetUserList(user);
            if (userlist.Count > 0)
            {
                user.ID = userlist[0].ID;
                user.Conditaion = null;
                user.Password = password;
                UserService.UpdateUser(user);
                ModelState.AddModelError("", "密码修改成功");
            }
            else
            {
                ModelState.AddModelError("", "旧密码错误");
            }
            return View();
        }

        public ActionResult Profile()
        {
            return View();
        }
        #endregion
        ////
        //// GET: /Admin/User/

        //public ActionResult Index()
        //{
        //    return View();
        //}

        ////
        //// GET: /Admin/User/Details/5

        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        ////
        //// GET: /Admin/User/Create

        //public ActionResult Create()
        //{
        //    return View();
        //} 

        ////
        //// POST: /Admin/User/Create

        //[HttpPost]
        //public ActionResult Create(FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add insert logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        ////
        //// GET: /Admin/User/Edit/5

        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        ////
        //// POST: /Admin/User/Edit/5

        //[HttpPost]
        //public ActionResult Edit(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add update logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        ////
        //// GET: /Admin/User/Delete/5

        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        ////
        //// POST: /Admin/User/Delete/5

        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

VipSoft.Web/Areas/VipSoft/Views/Shared/AdminBase.cshtml
<link href="@Url.Content("~/Scripts/ligerUI/skins/Aqua/css/ligerui-all.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/themes/Admin/style.css")" rel="stylesheet" type="text/css" />

<script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/ligerUI/js/ligerBuild.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Admin/VipSoft.Common.js")" type="text/javascript"></script>

<link href="@Url.Content("~/Scripts/artDialog/skins/blue.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/artDialog/artDialog.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/artDialog/artDialog.plugins.js")" type="text/javascript"></script>

VipSoft.Web/Areas/VipSoft/Views/Shared/_AdminLayout - Copy.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>依软内容管理系统-@ViewBag.Title</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="@Url.Content("~/Content/themes/base/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/font-awesome.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/fullcalendar.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery-ui.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/select2.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.jscrollpane.css")" rel="stylesheet" type="text/css" />
    
    
    <link href="@Url.Content("~/Scripts/layer/skin/layer.css")" rel="stylesheet" type="text/css" />

    <link href="@Url.Content("~/Content/themes/Admin/icheck/flat/blue.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/Admin/unicorn.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/Admin/unicorn.grey.css")"  class="skin-color" rel="stylesheet" type="text/css" />

    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.min.js")"></script>

    @RenderSection("Style", false)
</head>
<body>
    <div id="header">
        <h1><a href="#">VipSoft Admin</a></h1>
        <a id="menu-trigger" href="http://www.vipsoft.com.cn" target="_blank"><i class="fa fa-align-justify"></i></a>
    </div>

    <div id="search" class="unrealized">
        <input type="text" placeholder="Search here..." />
        <button type="submit" class="tip-right" title="Search" onclick="unrealized()"><i class="fa fa-search"></i></button>
    </div>
    <div id="user-nav">
        <ul class="btn-group">
           
                <li class="btn unrealized"><a title="" href="@Url.Action("Profile","User")"><i class="fa fa-user"></i><span class="text" >Profile</span></a></li>
                <li class="btn dropdown unrealized" id="menu-messages"><a href="#" data-toggle="dropdown" data-target="#menu-messages" class="dropdown-toggle"><i class="fa fa-envelope"></i><span class="text">Messages</span> <span class="label label-danger">5</span> <b class="caret"></b></a>
                    <ul class="dropdown-menu unrealized">
                        <li><a class="sAdd" title="" href="#" onclick="unrealized()">new message</a></li>
                        <li><a class="sInbox" title="" href="#" onclick="unrealized()">inbox</a></li>
                        <li><a class="sOutbox" title="" href="#" onclick="unrealized()">outbox</a></li>
                        <li><a class="sTrash" title="" href="#" onclick="unrealized()">trash</a></li>
                    </ul>
                </li>
                <li class="btn unrealized"><a title="" href="@Url.Action("Index","Config")"><i class="fa fa-cog"></i><span class="text">Settings</span></a></li>
        <!--
            <li class="btn unrealized"><a title="" href="@Url.Action("ChangePassword","User")"><i class="fa fa-cog"></i><span class="text">修改密码</span></a></li>
            -->
            <li class="btn"><a title="" href="@Url.Action("login","User")"><i class="fa fa-share"></i><span class="text" >退出</span></a></li>
        </ul>
    </div>

    @{Html.RenderAction("AdminMenu", "Menu");}

    <div id="style-switcher">
        <i class="fa fa-arrow-left"></i>
        <span>Style:</span>
        <a href="#grey" style="background-color: #555555; border-color: #aaaaaa;"></a>
        <a href="#light-blue" style="background-color: #8399b0;"></a>
        <a href="#blue" style="background-color: #2D2F57;"></a>
        <a href="#red" style="background-color: #673232;"></a>
        <a href="#red-green" style="background-image: url('/Uploads/demo/red-green.png'); background-repeat: no-repeat;"></a>
    </div>
    <div id="content" >
        <div id="content-header">
        <h1>@ViewBag.Title</h1>
        <ul class="mini-stats box-3">
            <li>
                <div class="left sparkline_bar_good"><span>2,4,9,7,12,10,12</span>+10%</div>
                <div class="right">
                    <strong>36094</strong>
                    Visits
                </div>
            </li>
            <li>
                <div class="left sparkline_bar_neutral"><span>20,15,18,14,10,9,9,9</span>0%</div>
                <div class="right">
                    <strong>1433</strong>
                    Users
                </div>
            </li>
            <li>
                <div class="left sparkline_bar_bad"><span>3,5,9,7,12,20,10</span>+50%</div>
                <div class="right">
                    <strong>8650</strong>
                    Orders
                </div>
            </li>
        </ul>
    </div>
    <div id="breadcrumb">
        <a href="#" title="Go to Home" class="tip-bottom"><i class="fa fa-home"></i>Home</a>
        <a href="#" class="current">Main</a>
    </div>
        @RenderBody()
    </div>
    <div class="row">
        <div id="footer" class="col-xs-12">
            Copyright &copy; 2007 - 2013 <a href="http://www.vipsoft.com.cn/">VipSoft.com.cn</a> Inc. All Rights Reserved.         
        </div>
    </div>
    <script type="text/javascript" src="@Url.Content("~/Scripts/excanvas.min.js")"></script>

    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-ui.custom.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
    <!--
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.flot.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.flot.resize.min.js")"></script>
    -->
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.sparkline.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.dataTables.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.icheck.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.jpanelmenu.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.nicescroll.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.history.js")"></script>  

    <script type="text/javascript" src="@Url.Content("~/Scripts/fullcalendar.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/select2.min.js")"></script>
    
    <script type="text/javascript" src="@Url.Content("~/Scripts/layer/layer.min.js")"></script>


    <script type="text/javascript" src="@Url.Content("~/Scripts/Admin/unicorn.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/Admin/unicorn.tables.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/Admin/unicorn.dashboard.js")"></script>
     @RenderSection("Script", false)
</body>
</html> 